pytest:
  tags:
    - conda
  stage: test
  before_script:
    - python3 -m pip install -r requirements.txt
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
